#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

LUMINOVO_NUM_CPUS="8"
LUMINOVO_RUST_TOOLCHAIN="nightly"

# eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"
