#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export EDITOR="nvim"
export VISUAL="$EDITOR"
export SYSTEMD_EDITOR="$EDITOR"

# export FZF_DEFAULT_COMMAND='rg -u --files '
export FZF_DEFAULT_COMMAND='fd --follow --exclude ".git" --type f'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PATH=~/.cargo/bin:$PATH
export PATH=~/.garden/bin:$PATH
export PATH=~/.poetry/bin:$PATH


# if [[ -z "$TMUX" ]] ;then
    # ID="$( tmux ls | grep -vm1 attached | cut -d: -f1 )" # get the id of a deattached session
    # if [[ -z "$ID" ]] ;then # if not available create a new one
        # tmux new-session
    # else
        # tmux attach-session -t "$ID" # if available attach to it
    # fi
# fi

#### zoxide
_zoxide_precmd() {
    zoxide add
}

[[ -n "${precmd_functions[(r)_zoxide_precmd]}" ]] || {
    precmd_functions+=(_zoxide_precmd)
}

z() {
    if [ $# -ne 0 ]; then
        _Z_RESULT=$(zoxide query "$@")
        case $_Z_RESULT in
            "query: "*)
                cd "${_Z_RESULT:7}"
                ;;
            *)
                echo "${_Z_RESULT}"
                ;;
        esac
    fi
}

alias zi="z -i"

alias za="zoxide add"
alias zq="zoxide query"
alias zr="zoxide remove"
#### /zoxide

autoload -Uz zmv
alias ls="exa --group-directories-first"
alias la="ll -a"
alias vim=nvim
alias tree=exa -T
alias k=kubectl
alias kn="kubectl -n"
alias mc="make check"
alias mf="make format"

# PGO things
export PATH=/home/tomas/.pgo/pgo:$PATH
export PGOUSER=/home/tomas/.pgo/pgo/pgouser
export PGO_CA_CERT=/home/tomas/.pgo/pgo/client.crt
export PGO_CLIENT_CERT=/home/tomas/.pgo/pgo/client.crt
export PGO_CLIENT_KEY=/home/tomas/.pgo/pgo/client.key
export PGO_APISERVER_URL='https://127.0.0.1:8443'

source <(kubectl completion zsh)

