# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export EDITOR="nvim"
export VISUAL="$EDITOR"
export SYSTEMD_EDITOR="$EDITOR"

# export FZF_DEFAULT_COMMAND='rg -u --files '
export FZF_DEFAULT_COMMAND='fd --follow --exclude ".git" --type f'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PATH=~/.cargo/bin:$PATH
export PATH=~/.garden/bin:$PATH
export PATH=~/.poetry/bin:$PATH
export PATH=~/.yarn/bin:$PATH


# if [[ -z "$TMUX" ]] ;then
    # ID="$( tmux ls | grep -vm1 attached | cut -d: -f1 )" # get the id of a deattached session
    # if [[ -z "$ID" ]] ;then # if not available create a new one
        # tmux new-session
    # else
        # tmux attach-session -t "$ID" # if available attach to it
    # fi
# fi

#### zoxide
eval "$(zoxide init zsh)"
#### /zoxide

autoload -Uz zmv
alias ls="exa --group-directories-first"
alias la="ll -a"
alias vim=nvim
alias tree=exa -T
alias k=kubectl
alias kn="kubectl -n"
alias mc="make check"
alias mf="make format"

# PGO things
export PATH=/home/tomas/.pgo/pgo:$PATH
export PGOUSER=/home/tomas/.pgo/pgo/pgouser
export PGO_CA_CERT=/home/tomas/.pgo/pgo/client.crt
export PGO_CLIENT_CERT=/home/tomas/.pgo/pgo/client.crt
export PGO_CLIENT_KEY=/home/tomas/.pgo/pgo/client.key
export PGO_APISERVER_URL='https://127.0.0.1:8443'

source <(kubectl completion zsh)

# Pyenv things
export PATH=$(pyenv root)/shims:$PATH
eval "$(pyenv init -)"

# LinkerD
export PATH=$PATH:/home/tomas/.linkerd2/bin

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
